### ISSUE TITLE
Animated GIF Broken

### ISSUE THREAD

**Issue by touhonoob** [cubicdaiya/ngx_small_light#25]
Example: http://i.imgur.com/mDsYBAU.gif

small_light(of=gif) Outputs: http://i.imgur.com/IXVsWRC.gif

**Comment by cubicdaiya** [comment]
I have no plan to support a transformation for an animated GIF. Because it takes long time to transform(e.g. resize, crop) an animated GIF with animation. So it is not realistic for `ngx_small_light` to support an animated GIF.
