### ISSUE TITLE
How to disable changing url pattern to visitors

### ISSUE THREAD

**Issue by fattalgazi** [cubicdaiya/ngx_small_light#27]
Hi,

I want to ask a question, 

When I enter this url : 

http://localhost/small_light(blur=8x8,dw=500,dh=500,q=50,e=imagemagick,of=jpg)/upload/test.jpg

I see blurred version of test.jpg, it is ok.

But I want to disable users to change this params, namely, if users clear blur=8x8 parameter he/she can see unblurred image.

So is there any hash protection that we can create, so users can not modify the url.

sorry for bad english.

**Comment by cubicdaiya** [comment]
`ngx_small_light` self does not have the features such as hash protection and param limitation.
If you want to achieve them, you might combine the another server program(e.g. ngx_lua) and `ngx_small_light`.

**Comment by midorinet** [comment]
You can also define it by using small_light_pattern_define
