### ISSUE TITLE
Setting url pattern

### ISSUE THREAD

**Issue by fattalgazi** [cubicdaiya/ngx_small_light#29]
Hello, 

Cant we set url pattern in nginx conf ?

When I set like that: 

    location ~ pic[^/]*/(.+)$ {
        set $file $1;
        rewrite ^ /$file;
    }

URL/pic(blur=8x8)/blabla.jpg not working, I see image but not blurred.

**Comment by cubicdaiya** [comment]
The url pattern is fixed. `small_light` must be included.

See [Configuration Example](https://github.com/cubicdaiya/ngx_small_light#configuration-example).
