### ISSUE TITLE
Images with orientation value not rotated correctly

### ISSUE THREAD

**Issue by tmorehouse** [cubicdaiya/ngx_small_light#35]
ImageMagick has an option for respecting the image's orientation flag, but currently small_light does not enable this feature..The option is called `AutoOrient`.

Currently when an image with an orientation flag, say 90 degrees, the image when scaled by small_light is as if the orientation flag was set at 0.degrees.

Would it be possible to either make `AutoOrient` the default, or to add in an option to enable this feature?

**Comment by cubicdaiya** [comment]
Thank you for the report. I'll investigate in the near future.

**Comment by tmorehouse** [comment]
thanks.

The auto orient feature would be great. (either as a flag or the default for ImageMagick).  I don't believe that GD has an equivalent option.

**Comment by cubicdaiya** [comment]
Hi @tmorehouse ,

I added new paramter（ `autoorient` ). Given `autoorient=y` to small_light function, ngx_small_light calls `MagickAutoOrientImage()` from 717068bafc8915b28edc21269cf7796a4046a53c.

**Comment by tmorehouse** [comment]
Excellent!

I shall try this out.
