### ISSUE TITLE
rmprof behavior do not match document.

### ISSUE THREAD

**Issue by chiastolite** [cubicdaiya/ngx_small_light#37]
Default rmprof prameter value is written as 'y' in the document.
But it seem to work as 'n'.

`small_light(e=imagemagick)/image.jpg` result  were the same as `small_light(e=imagemagick,rmprof=n)/image.jpg`

I think thant ngx_http_small_light_parse_flag is used only to default value 'n' parameter.

SEE ALSO
 https://github.com/cubicdaiya/ngx_small_light/blob/20375cc31ab657ebb2e9a691ee08daa8a8aea5d0/src/ngx_http_small_light_parser.c#L116
https://github.com/cubicdaiya/ngx_small_light/blob/892be931a2390007f27a0aa7ce79cf769e1a981c/src/ngx_http_small_light_imagemagick.c#L121

**Comment by cubicdaiya** [comment]
As `rmprof=n` is the expected behavior by default, fixed the documentation (https://github.com/cubicdaiya/ngx_small_light/commit/4b56f948148f6f9a237272807c1c1ba338b3445c). Thanks.

**Comment by chiastolite** [comment]
I see. Thanks! :smile:
