### ISSUE TITLE
WebP is not supported

### ISSUE THREAD

**Issue by djgxp** [cubicdaiya/ngx_small_light#40]
Hello unlike what you said in your description, I'm seeing in the code a message saying that webP is not supported in imageMagick and also in GD.

Will you support webP soon or is there anyway to make it work ?

**Comment by cubicdaiya** [comment]
No, `ngx_small_light` supports WebP manipulation with ImageMagick and GD. (FYI, ImageMagick is more recommended than GD.)

To supplement, `ngx_small_light` writes such as the message below to log when WebP is not available in spite of giving `of=webp`.

```
WebP is not supported
```

For WebP manipulation, ImageMagick requires libwebp and GD requires libvpx. The message above is output to log when these libraries are not embedded.

**Comment by midorinet** [comment]
Hello

I got the same error

**Comment by cubicdaiya** [comment]
@midorinet 

If the WebP manipulation with ImageMagick is enabled, the output of `convert -list format` includes the line like below.

```bash
$ convert -list format | grep -i webp
     WEBP* WEBP      rw-   WebP Image Format (libwebp 0.5.0[0208])
```

If the line above is not included, you need to recompile ImageMagick, too.

FYI, do you use the provided package from linux distribution such as CentOS and Ubuntu? Usually such package does not built-in the WebP support by default.

**Comment by devendra-dhayal** [comment]
Hello
I got the same error:
WebP is not supported ngx_http_small_light_imagemagick_process:493
The output of the command "$ convert -list format | grep -i webp" is:
 WEBP* rw-   WebP Image Format (libwebp 0.4.4[0208])

But still getting the same error.

Any help will be appreciated.

**Comment by rakeshgithub** [comment]
@cubicdaiya 
I have compiled ImageMagick for WebP support and then checked this with convert -list command and received the expected result.
`

>  convert -list format | grep -i webp
>      WEBP* rw-   WebP Image Format (libwebp 0.6.0[0208])

`
Still, when I see the logs, I found the following error:

2018/11/13 23:38:13 [error] 2862#2862: *129 WebP is not supported ngx_http_small_light_imagemagick_process:493 while sending response to client, client: 127.0.0.1, server: localhost, request: "GET /small_light(,of=webp

Any advice?

**Comment by rakeshgithub** [comment]
> @cubicdaiya
> I have compiled ImageMagick for WebP support and then checked this with convert -list command and received the expected result.
> `
> 
> > convert -list format | grep -i webp
> > WEBP* rw-   WebP Image Format (libwebp 0.6.0[0208])
> 
> `
> Still, when I see the logs, I found the following error:
> 
> 2018/11/13 23:38:13 [error] 2862#2862: *129 WebP is not supported ngx_http_small_light_imagemagick_process:493 while sending response to client, client: 127.0.0.1, server: localhost, request: "GET /small_light(,of=webp
> 
> Any advice?

I have first compiled nginx and then ImageMagick with libwebp. Shall I recompile nginx ?
