### ISSUE TITLE
Return white image when the png image contain offset

### ISSUE THREAD

**Issue by hienbx94** [cubicdaiya/ngx_small_light#44]
I have a png image contain offset
`bash: identify a.png`
`a.png PNG 480x220 480x580+0+360 8-bit DirectClass 65KB 0.000u 0:00.000`

![a](https://cloud.githubusercontent.com/assets/7977399/16553769/bc4ed77c-41f4-11e6-8de1-1c78e433c022.png)

when i try resize image with `small_light(dw=230,da=l,ds=n)` but it return white image
when i using param `sy = value of offset` (`small_light(dw=230,da=l,ds=n,sy=360)`), it is correct
Can you explain this case?

**Comment by cubicdaiya** [comment]
Maybe `MagickResetImagePage(ictx->wand, "+0+0");` is required for such image.

**Comment by lannp** [comment]
@cubicdaiya 
I have same problem
I try your solution, but it can't fix.
I think reason is: png have ` png:oFFs : x_off  y_off`. So when param have `sy=360`(with image above), we have this image. When param not have `sy`, we have a blank image

**Comment by hienbx94** [comment]
@cubicdaiya 
I tried your solution, it is ok.
Thank you!

**Comment by cubicdaiya** [comment]
@lannp 

Now ngx_small_light does not consider about image offset. I think ngx_small_light should control it automatically. If that's ok, would you provide sample image?

**Comment by lannp** [comment]
@cubicdaiya 
Sorry, I tried again, it fixed
The first time, It only scale `dw`, so image is error. I changed again, it fixed
Thank you

**Comment by cubicdaiya** [comment]
Fixed in #48.
