### ISSUE TITLE
why request param of=webp,but return type Content-Type:image/png or others type?

### ISSUE THREAD

**Issue by luoyanjun0000** [cubicdaiya/ngx_small_light#51]

**Comment by cubicdaiya** [comment]
If WebP manipulation is enabled, the value of returned Content-Type is set `image/webp` when `of=webp` is given.

Is the line like below output in your error.log? If it is so, you need to re-compile ImageMagick with libwebp.

```
WebP is not supported
```

If WebP manipulation with ImageMagick is enabled, the output of `convert -list format` includes the line like below.

```
% convert -list format | grep -i webp
     WEBP* WEBP      rw-   WebP Image Format (libwebp 0.5.0[0208])
```
