### ISSUE TITLE
Wand-config not found on Debian Jessie

### ISSUE THREAD

**Issue by midorinet** [cubicdaiya/ngx_small_light#53]
I got error Wand-config is not found

However I got libmagickwand-dev installed. Can you please advice?

ii  libmagick++-6-headers              8:6.8.9.9-5+deb8u2            all          object-oriented C++ interface to ImageMagick - header files
ii  libmagick++-6.q16-5:amd64          8:6.8.9.9-5+deb8u2            amd64        object-oriented C++ interface to ImageMagick
ii  libmagick++-6.q16-dev:amd64        8:6.8.9.9-5+deb8u2            amd64        object-oriented C++ interface to ImageMagick - development files
ii  libmagick++-dev                    8:6.8.9.9-5+deb8u2            all          object-oriented C++ interface to ImageMagick
ii  libmagickcore-6-arch-config:amd64  8:6.8.9.9-5+deb8u2            amd64        low-level image manipulation library - architecture header files
ii  libmagickcore-6-headers            8:6.8.9.9-5+deb8u2            all          low-level image manipulation library - header files
ii  libmagickcore-6.q16-2:amd64        8:6.8.9.9-5+deb8u2            amd64        low-level image manipulation library -- quantum depth Q16
ii  libmagickcore-6.q16-2-extra:amd64  8:6.8.9.9-5+deb8u2            amd64        low-level image manipulation library - extra codecs (Q16)
ii  libmagickcore-6.q16-dev:amd64      8:6.8.9.9-5+deb8u2            amd64        low-level image manipulation library - development files (Q16)
ii  libmagickcore-dev                  8:6.8.9.9-5+deb8u2            all          low-level image manipulation library -- transition package
ii  libmagickwand-6-headers            8:6.8.9.9-5+deb8u2            all          image manipulation library - headers files
ii  libmagickwand-6.q16-2:amd64        8:6.8.9.9-5+deb8u2            amd64        image manipulation library
ii  libmagickwand-6.q16-dev:amd64      8:6.8.9.9-5+deb8u2            amd64        image manipulation library - development files
ii  libmagickwand-dev                  8:6.8.9.9-5+deb8u2            all          image manipulation library - transition for development files

**Comment by midorinet** [comment]
Editing setup file then doing hardcode for wand_libs wand_lds wand_includes fixed the problem

**Comment by cubicdaiya** [comment]
Could you provide the linux distribution you use, please?

**Comment by cubicdaiya** [comment]
> Wand-config not found on Debian Jessie

Sorry. I missed the titile.
