### ISSUE TITLE
Animated GIF Check

### ISSUE THREAD

**Issue by midorinet** [cubicdaiya/ngx_small_light#54]
Since converting GIF image was disabled on small_light, is there any posibility to have frame checking before converting?

1 of ImageMagick package is "identify", below is the sample output
# identify -format %n smilies_fbejiqljqkd1.gif
12

# identify -format %n avatar120909_5.gif
1

So let say the output equal 1, then small_light will convert it to webp

If the output is > 1, then don't convert to webp

**Comment by cubicdaiya** [comment]
> Since converting GIF image was disabled on small_light, is there any posibility to have frame checking before converting?

No. 

> If the output is > 1, then don't convert to webp

No. if animated GIF is given to small_light, only its first frame is converted. It is the expected behavior.
