### ISSUE TITLE
after install libwebp 

### ISSUE THREAD

**Issue by luoyanjun0000** [cubicdaiya/ngx_small_light#55]
sorry, My English is not very good，so that the question description is unclear.

,after install libwebp ,in linux conmand line run "convert a.jpg b.webp" is success, but usr small_light still failed. i'm try my localhost http://192.168.56.110:8087/b.webp is ok ,but http://192.168.56.110:8087/small_light(of=png)/b.webp is failed, the erro "415 Unsupported Media Type" nginx error log "*30 couldn't read image ngx_http_small_light_imagemagick_process:114"

**Comment by cubicdaiya** [comment]
Hi @luoyanjun0000,

Please write not only title but description, too. It is very unreadable.

**Comment by cubicdaiya** [comment]
@luoyanjun0000 

> "convert a.jpg b.webp" is success

Provide the output of `identify b.webp`, please.

**Comment by luoyanjun0000** [comment]
ouput " WEBP* rw-   WebP Image Format (libwebp 0.5.1 [0208])", install imagemagick need libwebp？？

**Comment by cubicdaiya** [comment]
> the erro "415 Unsupported Media Type" nginx error log "*30 couldn't read image ngx_http_small_light_imagemagick_process:114"

If ImageMagick embedded libwebp is installed and used, the error above is not occured at least.

**Comment by cubicdaiya** [comment]
> install imagemagick need libwebp？？

Yes.

**Comment by luoyanjun0000** [comment]
install imagemagick 7.0+,run small_light directory conmand "./setup" ,throw error "which: no Wand-config in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
Wand-config is not found"

**Comment by cubicdaiya** [comment]
Is there `MagickWand-config` instead of `Wand-config`?

**Comment by luoyanjun0000** [comment]
yes, /usr/local/bin/MagickWand-config is exist.

**Comment by luoyanjun0000** [comment]
i "cp" another?

**Comment by cubicdaiya** [comment]
As ImageMagick-7.0+ is not supported yet, use ImageMgick-6.9.x or replace `Wand-config` to `MagickWand-config`.

**Comment by luoyanjun0000** [comment]
after install ImageMagick-7.0+ ,i can't install libwebp, convert webp style is ok.

**Comment by luoyanjun0000** [comment]
before can't convert webp，because of i install Imagemagick by "yum install Imagemagick" command,
