### ISSUE TITLE
How to auto-crop / trim?

### ISSUE THREAD

**Issue by agaoglu** [cubicdaiya/ngx_small_light#58]
I couldn't find a way to do it currently but AFAIK imagemagick has this kind of operation, i don't know about the others though. Anyways, would it be too hard? Would you have any pointers if i try to contribute it?

**Comment by cubicdaiya** [comment]
> I couldn't find a way to do it currently but AFAIK imagemagick has this kind of operation, i don't know about the others though. Anyways, would it be too hard? Would you have any pointers if i try to contribute it?

Is it like the option `-trim` of `convert`? Now `ngx_small_light` does not support the such feature. But patches welcome.
