### ISSUE TITLE
WebP on mozilla firefox

### ISSUE THREAD

**Issue by draskolnikova** [cubicdaiya/ngx_small_light#62]
Hello!

Since firefox not yet support WebP image processing, is there any tips for load image(s) using `of=webp` on firefox? Because the image(s) won't load

**Comment by cubicdaiya** [comment]
`ngx_small_light` does not have the responsibility for the non-support feature of browsers. Correspond application side.

BTW, please don't open issue as question non-related `ngx_small_light` directly. Ask in more general forums about the question like above.
