### ISSUE TITLE
Resize Bigger than Original File

### ISSUE THREAD

**Issue by midorinet** [cubicdaiya/ngx_small_light#67]
I have a file which is 100x100 pixels. However, the code resize it to bigger size eg. 250x250 pixels. ngx_small_lights module will expand the picture to 250x250px so the quality is worse. Is there any way that we should return the original file which is 100x100px instead of make it 250x250px?

**Comment by cubicdaiya** [comment]
Give `pt=y` to small_light function.

**Comment by midorinet** [comment]
I tried with

?pt=y&dw=250&dh=250
It's still streched

**Comment by cubicdaiya** [comment]
Sorry. I jumped to conclusions. Though ngx_small_light does not resize image when destination size is large than original size, it may be the bug.

How about trying to apply the patch below and give `pt=ptss`?

```diff
diff --git a/src/ngx_http_small_light_size.c b/src/ngx_http_small_light_size.c
index b25d4c3..48ecb74 100644
--- a/src/ngx_http_small_light_size.c
+++ b/src/ngx_http_small_light_size.c
@@ -119,11 +119,11 @@ void ngx_http_small_light_calc_image_size(ngx_http_request_t *r,
     pt_flg = 0;
     pt     = NGX_HTTP_SMALL_LIGHT_PARAM_GET_LIT(&ctx->hash, "pt");
     if (pt[0] == '\0' || ngx_strcmp(pt, "ptss") == 0) {
-        if (sz->sw < sz->cw && sz->sh < sz->ch) {
+        if (sz->sw < sz->dw && sz->sh < sz->dh) {
             pt_flg = 1;
         }
     } else if (ngx_strcmp(pt, "ptls") == 0) {
-        if (sz->sw > sz->cw || sz->sh > sz->ch) {
+        if (sz->sw > sz->dw || sz->sh > sz->dh) {
             pt_flg = 1;
         }
     }
```

**Comment by midorinet** [comment]
tried the above patch

and accessing 
`?dw=720&dh=720&pt=ptss`
still have the same results

**Comment by midorinet** [comment]
`?dw=720&dh=720&pt=ptls`
these command works

Should we use ptls instead of ptss?

**Comment by cubicdaiya** [comment]
ngx_small_light outputs the message like below when error_log level is more than `notice`. Would you paste the output in your environment?

```
2016/09/08 07:19:00 [notice] 92539#0: *1 size info:sx=0,sy=0,sw=10000,sh=10000,dw=200,dh=200,dx=-100,dy=-100,cw=0,ch=0,bw=0,bh=0,ix=0,iy=0 while sending response to client, client: 127.0.0.1, server: , request: "GET /s.png?dw=200&dh=200&pt=ptss HTTP/1.1", host: "127.0.0.1"
2016/09/08 07:19:00 [notice] 92539#0: *1 size info:sx=0,sy=0,sw=78,sh=100,dw=156,dh=200,dx=-78,dy=-100,cw=0,ch=0,bw=0,bh=0,ix=0,iy=0 while sending response to client, client: 127.0.0.1, server: , request: "GET /s.png?dw=200&dh=200&pt=ptss HTTP/1.1", host: "127.0.0.1"
```

**Comment by midorinet** [comment]
Below are the results

> 2016/09/08 19:36:37 [notice] 22444#22444: *91 size info:sx=0,sy=0,sw=10000,sh=10000,dw=720,dh=720,dx=-360,dy=-360,cw=0,ch=0,bw=0,bh=0,ix=0,iy=0 while sending to client, client: x.x.x.x, server: , request: "GET /images/2016/08/18/8813224_201608180827350480.jpg?dw=720&dh=720&pt=ptss HTTP/1.1", upstream: "http://y.y.y.y:80/images/2016/08/18/8813224_201608180827350480.jpg?p=perf&dw=720&dh=720&pt=ptss", host: "x.x.x.x"
> 2016/09/08 19:36:37 [notice] 22444#22444: *91 size info:sx=0,sy=0,sw=920,sh=558,dw=720,dh=436,dx=-360,dy=-218,cw=0,ch=0,bw=0,bh=0,ix=0,iy=0 while sending to client, client: x.x.x.x, server: , request: "GET /images/2016/08/18/8813224_201608180827350480.jpg?dw=720&dh=720&pt=ptss HTTP/1.1", upstream: "http://y.y.y.y:80/images/2016/08/18/8813224_201608180827350480.jpg?p=perf&dw=720&dh=720&pt=ptss", host: "x.x.x.x"

**Comment by midorinet** [comment]
hello, any idea how to fix it?

**Comment by cubicdaiya** [comment]
Sorry for late. Now I'm busy for business trip. After returned I'll check it.

**Comment by cubicdaiya** [comment]
@midorinet As far as I see your log: https://github.com/cubicdaiya/ngx_small_light/issues/67#issuecomment-245583656, your original image is bigger than resized image. ( sw=920,sh=558,dw=720,dh=436 )

I'm saying the same thing again, ngx_small_light does not resize image when destination size is large than original size, it may be the bug.

**Comment by midorinet** [comment]
thanks for your clarification. Is there any patch that I could try? :)

**Comment by midorinet** [comment]
Hi

I tried the above patch. However when I give ?dw=60&dh=60&pt=ptls it doesn't work

**Comment by cubicdaiya** [comment]
What behavior do you expect?

**Comment by midorinet** [comment]
If the resized is smaller than original, then it's still resizing to the
smaller size

**Comment by cubicdaiya** [comment]
> If the resized is smaller than original, then it's still resizing to the smaller size

It's normal behavior. `pt=ptls` is used for passing original image without resizing. If you want to resize, `pt` is not required.

**Comment by midorinet** [comment]
Hi

The problem is we don't know wether the image is bigger or smaller

**Comment by cubicdaiya** [comment]
I'm saying the same thing again and again, ngx_small_light does not resize image when destination size is bigger than original size. Does your destination image really become bigger than original image?  If it is so, it is a bug. Unfortunately I could have not reproduce it.

**Comment by midorinet** [comment]
Here's the example

http://103.6.117.8/images/2016/08/18/8813224_201608180827350480.jpg --> Original file
http://103.6.117.8/images/2016/08/18/8813224_201608180827350480.jpg?dw=720&dh=720 --> Streched
http://103.6.117.8/images/2016/08/18/8813224_201608180827350480.jpg?dw=720&dh=720&pt=ptls --> Works as expected
http://103.6.117.8/images/2016/08/18/8813224_201608180827350480.jpg?dw=60&dh=60 --> Works
http://103.6.117.8/images/2016/08/18/8813224_201608180827350480.jpg?dw=60&dh=60&pt=ptls

**Comment by cubicdaiya** [comment]
Though I checked the URLs above, all are 404 Not Found.

**Comment by midorinet** [comment]
Hmm it's weird. Can you please retry now?

**Comment by cubicdaiya** [comment]
Certainly the image downloaded from your site is bigger than original file.
But, I could have not reproduce it though I got the original file above and converted with ngx_small_light.

```
$ identify orig.jpg
orig.jpg JPEG 460x279 460x279+0+0 8-bit sRGB 38.1KB 0.000u 0:00.000
$ curl -s "http://127.0.0.1:8089/a/orig.jpg?dw=720&dh=720" > hoge.jpg
$ identify hoge.jpg
hoge.jpg JPEG 460x279 460x279+0+0 8-bit sRGB 39.6KB 0.000u 0:00.000
```

And the result from notice log is different from yours.

```
2016/09/20 09:08:49 [notice] 65741#891509: *1 size info:sx=0,sy=0,sw=10000,sh=10000,dw=720,dh=720,dx=-360,dy=-360,cw=0,ch=0,bw=0,bh=0,ix=0,iy=0 while sending response to client, client: 127.0.0.1, server: , request: "GET /a/orig.jpg?dw=720&dh=720 HTTP/1.1", host: "127.0.0.1:8089"
2016/09/20 09:08:49 [notice] 65741#891509: *1 size info:sx=0,sy=0,sw=460,sh=279,dw=720,dh=436,dx=-360,dy=-218,cw=0,ch=0,bw=0,bh=0,ix=0,iy=0 while sending response to client, client: 127.0.0.1, server: , request: "GET /a/orig.jpg?dw=720&dh=720 HTTP/1.1", host: "127.0.0.1:8089"
```

Would you provide the informations below?

* OS: ( `uname -ar`)
* nginx: ( `nginx -V`)
* ImageMagick: ( `convert --version` )

**Comment by midorinet** [comment]
Here's the information needed

> Linux origin 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux
> nginx version: nginx/1.10.1
> built by gcc 4.9.2 (Debian 4.9.2-10) 
> built with OpenSSL 1.0.1t  3 May 2016
> TLS SNI support enabled
> configure arguments: --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --without-http_upstream_ip_hash_module --without-http_scgi_module --without-http_uwsgi_module --without-http_auth_basic_module --with-http_ssl_module --add-module=/usr/local/src/ngx_cache_purge --with-http_realip_module --add-module=/usr/local/src/ngx_devel_kit --add-module=/usr/local/src/lua-nginx-module --add-module=/usr/local/src/set-misc-nginx-module --with-http_image_filter_module --with-threads --add-module=/usr/local/src/ngx_small_light
> Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-08-26 http://www.imagemagick.org
> Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
> Features: DPC Modules OpenMP
> Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff webp wmf x xml zlib
