### ISSUE TITLE
support tiff style

### ISSUE THREAD

**Issue by luoyanjun0000** [cubicdaiya/ngx_small_light#69]
imagemagick can convert tiff image, how can support tiff image by small_light?

**Comment by cubicdaiya** [comment]
Now ngx_small_light supports the formats below.

* JPEG
* PNG
* GIF
* WebP

Is there an use case required dynamic transformation for TIFF?

**Comment by luoyanjun0000** [comment]
yes,we have a case need transform for tiff,but i don't know how modify code,i'm a java coder.

**Comment by cubicdaiya** [comment]
I have no plan for supporting TIFF. Sorry.
