### ISSUE TITLE
Unable to write on /tmp against SELinux

### ISSUE THREAD

**Issue by draskolnikova** [cubicdaiya/ngx_small_light#70]
Hello!

I'm using nginx-1.11.4 and build with small_light f803388, but I have a problem with small_light and SELinux Enforcing servers, my configuration is looks like : 

```bash
        small_light_pattern_define image of=webp&e=imagemagick;
        small_light_imlib2_temp_dir /var/cache/nginx/small_light 1 2;
        small_light_buffer 8M;

        location ~ \.(jpe?g|png|gif|webp)$ {
                 small_light on;
                 small_light_getparam_mode on;
        }
```

My linux installation:
```
Linux fyg 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

The error logs : 
```
-- Unit nginx.service has begun starting up.
Sep 30 23:28:55 fyg nginx[31183]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Sep 30 23:28:55 fyg nginx[31183]: nginx: [emerg] chown("/tmp", 996) failed (13: Permission denied)
Sep 30 23:28:55 fyg nginx[31183]: nginx: configuration file /etc/nginx/nginx.conf test failed
```

We can see that `996` refers to nginx uid tried to change the owner of `/tmp` folder and SELinux denied  it. Any hints?

**Comment by cubicdaiya** [comment]
I don't know about SELinux very much. If possible, you can disable SELinux by `setenforce 0`. (To disable after reboot, it is required to edit **/etc/sysconfig/selinux**.

**Comment by draskolnikova** [comment]
@cubicdaiya I think since small_light using `ngx_path_init_t`, the module are check the temporary path for imlib2 are exists and writeable (even the I didn't use imlib2).

**Comment by cubicdaiya** [comment]
Patches welcome anytime.
