### ISSUE TITLE
The small-light setup script couldn't generate config file.

### ISSUE THREAD

**Issue by eccentricyan** [cubicdaiya/ngx_small_light#80]
```
brew install nginx-full --with-image-filter --with-small-light-module
```
```
Error: The small-light setup script couldn't generate config file.
```

**Comment by cubicdaiya** [comment]
As I'm not familiar with homebrew, how about issuing below?

https://github.com/Homebrew/homebrew-nginx

**Comment by denji** [comment]
Problem imagemagick-7.0.4-4.
Wand-config https://github.com/cubicdaiya/ngx_small_light/blob/v0.9.0/setup#L89-L99
```
==> ./setup
Wand-config is not found
ln -s ../Cellar/nginx-full/1.10.2/bin/nginx nginx
ln -s ../../../Cellar/nginx-full/1.10.2/share/man/man8/nginx.8 nginx.8
Error: The small-light setup script couldn't generate config file.
```

**Comment by denji** [comment]
$ /usr/local/opt/imagemagick/bin/MagickWand-config --version
7.0.4 Q16 HDRI

**Comment by eccentricyan** [comment]
@denji 
my imagemagick version is  7.0.4
how can i fix it?
change imagemagic version?

**Comment by cubicdaiya** [comment]
@eccentricyan @denji Thank you for the suggestion.

ngx_small_light does not support ImageMagick7 yet.

refs:https://github.com/cubicdaiya/ngx_small_light/issues/63

Can you downgrade ImageMaigck to 6.9.x?
