### ISSUE TITLE
x, y position of crop drift

### ISSUE THREAD

**Issue by urapico** [cubicdaiya/ngx_small_light#81]
I'm using ngx_small_light when I cropped a image.
I upgrade ngx_small_light to v0.8.0. Then it is occurred one problem.

I use like this parameter `sx=700,sy=500,sw=540,sh=405,dw=540,da=l,ds=s`.
I feel `sx` and `xy`  parameter was ignored.

Maybe I think below issue is relevant.
https://github.com/cubicdaiya/ngx_small_light/issues/44

**Comment by cubicdaiya** [comment]
@urapico Try #82.

**Comment by urapico** [comment]
@cubicdaiya Thank you. 👍 
I checked #82. And it resolved this problem. ✨
