### ISSUE TITLE
small_light_material_dir from s3

### ISSUE THREAD

**Issue by redbox-cdn** [cubicdaiya/ngx_small_light#93]
Hi. I have one question about small_light_material_dir. 
Would it be possible to get from the S3 image object ?

According to small_light_material_dir code, it can not seems to specify @location or another nginx location.

**Comment by cubicdaiya** [comment]
> Would it be possible to get from the S3 image object ?

No. `small_light_material_dir` specifies the local file path like **/path/to/materials**.

**Comment by redbox-cdn** [comment]
OK! thank you for quick answer
