### ISSUE TITLE
Is it possible to delete exif?

### ISSUE THREAD

**Issue by redbox-cdn** [cubicdaiya/ngx_small_light#94]
The ngx small light can be delete of Exit?
mod_small_light is able to choose delete or inherit of Exif.

**Comment by cubicdaiya** [comment]
ngx_small_light provides `rmprof` to delete all profile in image.

https://github.com/cubicdaiya/ngx_small_light#parameters-for-small_light-function

**Comment by redbox-cdn** [comment]
Hi thank you for information.
I understood your explanation
